service: orders

frameworkVersion: "3"
package:
  individually: true

provider:
  name: aws
  stage: dev
  runtime: nodejs20.x
  environment:
    TEST: test

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    external:
      - knex
    watch:
      pattern: "src/**/*.ts"
      ignore: "**/*.test.ts"

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  process-order-payment:
    handler: src/api/handlers/process-order-payment.handler
